### ISSUE TITLE
Doesn't compile out of source control

### ISSUE THREAD

**Issue by craftworkgames** [SoundGoddess/OpenSolitaire#1]
So I downloaded the code from github and ran into a compile error.

```
Unable to find manifest signing certificate in the certificate store.
```

I assume the reason is because the `OpenSolitaireMG_TemporaryKey.pfx` file is missing. One way to solve it would be to add that file to source control.

However, if you're okay with not signing the manifests I think that's probably a better solution. As far as I'm aware, most open source projects don't have signed manifests.

To turn off manifest signing I used these steps:
1. Right click the `OpenSolitareMG` project in Solution Explorer and got to Properties.
2. Click the Signing tab.
3. Uncheck the Sign ClickOnce manifests box.

After that everything compiles and runs nicely.

**Comment by SoundGoddess** [comment]
Cool, I went ahead and removed the signing for now.  Sorry that the code is a bit of a mess, this is my first little project and I'm just trying to get stuff working first and then I can clean up and refactor the code a bit later.  I haven't yet done anything with the Extended framework for this project specifically but I have been playing around with your demos :)

**Comment by craftworkgames** [comment]
Have you heard of a tool called [Resharper](https://www.jetbrains.com/resharper/). It's a really excellent extension for Visual Studio that helps you write and refactor your code. The end result is always very clean and consistent code. If you're just learning it'll teach you a lot just by using it.

It does cost a bit of money, but it's one of the few tools I bought the day the trial ran out. So it's well worth a look. Anyway, I better stop talking about it otherwise I'm going to sound like an ad :)

I'm looking forward to help you with the project, but I don't want to get in your way either. Let me know how you'd like to proceed when you're ready.

**Comment by SoundGoddess** [comment]
I've heard of Resharper but never tried it before.  Seems kind of expensive, but I'll give the demo a try.  I do have a license for IntelliJ IDEA, so I like the JetBrains stuff.

I'm looking at your InputListeners demo, it seems that I'd want to attach a mouseListener to the card object and then update the sprite position with a method from the MouseDrag event.

I think I'll go ahead and create a new separate project for MonoGameDragAndDrop since I feel like this functionality is sorely missing from the MG tutorials and documentation.  Once I figure out this aspect of things I think I can then work more on the solitaire game.  One of my goals is to have the solitaire game be a reference game for the MG project so that someone can have some code to play with to help them learn and understand MG.  I'm hoping that the uphill battle I feel I'm dealing with on this stuff will be smooth sailing for the next person since they can just follow my examples to get up and running quickly.  I want people to focus more on game design and less on having to dig through ancient XNA example code to try to get basic functionality working in MG.
